#+TITLE: Smart Jump

[[https://travis-ci.org/jojojames/smart-jump][file:https://travis-ci.org/jojojames/smart-jump.svg?branch=master]]

* About
  This packages tries to smartly go to definition leveraging several methods to
  do so.

  If one method fails, this package will go on to the next one, eventually
  falling back to [[https://github.com/jacktasia/dumb-jump][dumb-jump]]

* Install
  This is not on melpa yet so it needs to be cloned into a directory on Emacs'
  load-path.

  #+begin_src emacs-lisp :tangle yes
  (use-package smart-jump
    :load-path "~/.emacs.d/vendor/smart-jump"
    :ensure nil)
  #+end_src

* Examples
** Bare minimum example
   Sets up smart-jump for [[https://github.com/mooz/js2-mode][js2-mode]] with default settings. Defaults will use the
   built-in [[https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/xref.el][xref]] functions first and fall back to dumb-jump if that fails.

   #+begin_src emacs-lisp :tangle yes
   (smart-jump-register :modes '(js2-mode))
   #+end_src
** Multiple modes
   Sets up smart-jump for both emacs-lisp-mode and lisp-interaction-mode.
   #+begin_src emacs-lisp :tangle yes
   (smart-jump-register :modes '(emacs-lisp-mode lisp-interaction-mode)
                        :jump-fn 'elisp-slime-nav-find-elisp-thing-at-point
                        :pop-fn 'pop-tag-mark
                        :should-jump t
                        :heuristic 'error
                        :async nil)
   #+end_src
** Supporting Asynchronous Functions
   Sometimes GoToDefinition is written in an asynchronous fashion which makes it
   tricky to fallback to the next GoToDefinition method. This package supports
   that case. Just set the ~:async~ parameter.
   #+begin_src emacs-lisp :tangle yes
   (smart-jump-register :modes 'java-mode
                        :jump-fn 'ggtags-find-tag-dwim
                        :pop-fn 'ggtags-prev-mark
                        :should-jump t
                        :heuristic 'point
                        :async t)

   #+end_src

   #+begin_src emacs-lisp :tangle yes
   ;; This sets a custom timeout.
   (smart-jump-register :modes 'csharp-mode
                        :jump-fn 'omnisharp-go-to-definition
                        :pop-fn 'pop-tag-mark
                        :should-jump t
                        :heuristic 'point
                        :async 500)
   #+end_src
** Finding References with Fallback
   #+begin_src emacs-lisp :tangle yes
  (smart-jump-register :modes 'tide-mode
                       :jump-fn 'tide-jump-to-definition
                       :pop-fn 'tide-jump-back
                       :refs-fn 'tide-references
                       :should-jump t
                       :heuristic 'point
                       :async t)
   #+end_src

   Fallback for finding references can be customized with
   ~smart-jump-simple-find-references-function~.
** A more complex example
   Register different GoToDefinition functions with c-mode.

   In this case, the fallback strategy is ->

   - For Jumping
   ~rtags-find-symbol-at-point~ -> ~ggtags-find-tag-dwim~ -> ~dumb-jump-go~

   - For Finding References
   ~rtags-find-all-references-at-point~ -> ~ggtags-find-reference~ -> ~smart-jump-simple-find-references~

   #+begin_src emacs-lisp :tangle yes
  (smart-jump-register :modes '(c-mode c++-mode)
                       :jump-fn 'rtags-find-symbol-at-point
                       :pop-fn 'rtags-location-stack-back
                       :refs-fn 'rtags-find-all-references-at-point
                       :should-jump (lambda ()
                                      (and
                                       (fboundp 'rtags-executable-find)
                                       (rtags-executable-find "rc")
                                       (rtags-is-indexed)))
                       :heuristic 'point
                       :async 500)

  (smart-jump-register :modes '(c-mode c++-mode)
                       :jump-fn 'ggtags-find-tag-dwim
                       :pop-fn 'ggtags-prev-mark
                       :refs-fn 'ggtags-find-reference
                       :should-jump t
                       :heuristic 'point
                       :async 500)
   #+end_src
* Help Wanted :)
  ~smart-jump-register~ needs some work around developer ergonomics. It'd be
  better for it to be more idempotent so configuration changes can be reloaded
  on the fly.

  Add more fallback methods and/or language support plists.

  Async code handling is fairly duplicated.

  Add tests!

  Set up CI.
